### ISSUE TITLE
Error after removing new enemies

### ISSUE THREAD

**Issue by Martok88** [veden/Rampant#17]
I'm playing with new enemies enabled, and when fast enemies showed up, they completely wrecked me. I decided to disable them but keep the rest of the new enemies by commenting out "require("prototypes/Fast")" in data-final-fixes.lua.  This seemed to work, and I got a message about all the fast entities being removed when I loaded the game again. However, the game sometime crashes shortly afterwards. If I reload the exact same save after disabling them, it may or may not crash, and if it does it could be seconds or minutes until it happens. Here's a screenshot of the error:
![screenshot](https://i.imgur.com/X21m4oq.png)

I'm using the latest version of Factorio and Rampant. If you need any other info, let me know.

**Comment by veden** [comment]
More regions to comment to remove the faction.

https://github.com/veden/Rampant/blob/master/libs/BaseUtils.lua#L544
https://github.com/veden/Rampant/blob/master/libs/Constants.lua#L179
https://github.com/veden/Rampant/blob/master/libs/Constants.lua#L197

You also may want to flush all the caches by triggering a version change.

through the upgrade script

change the constants.VERSION_58 to the number 59
https://github.com/veden/Rampant/blob/master/Upgrade.lua#L220
https://github.com/veden/Rampant/blob/master/Upgrade.lua#L223

keep in mind that any new builds I create will be borked on your system if you use the cache flushing mechanism

otherwise you may should be able to cause a cache flush through modifying the rampant mod settings triggering a configuration change event.

**Comment by Martok88** [comment]
Thanks a lot, changing the version number seemed to fix it. What would it take to make future new versions compatible with my save? Just bumping the new version number up by 1?

Also, I'm not sure how simple it would be to implement, but do you think you could add an option to scale the new enemies separately from the vanilla ones? They are considerably stronger, and I'd prefer to nerf them a bit without affecting the standard enemies.

**Comment by veden** [comment]
Potentially bumping it should be fine.

Are you asking for scaling options on the non neutral biters aside form the unit level in the mod settings?

**Comment by Martok88** [comment]
That's exactly what I needed, I just didn't realize that it only affected the non-neutral enemies. How will lowering the end tier affect an existing save?

**Comment by veden** [comment]
Unit level affects all new enemy types including neutral, I was asking if that is what you wanted.

The unit level just scales the biter stats, if you raise or lower it in a save, it will modify the enemies in-place as long as you don't change the number of tiers or variations

**Comment by Martok88** [comment]
Ok, I think I understand. I feel like the neutral ones aren't really a threat compared to everything else, but I should be able to make them stronger fairly easily. Thanks again for your help.
