### ISSUE TITLE
multiplayer desync

### ISSUE THREAD

**Issue by axaluss** [veden/Rampant#32]
We were playing for many hours but lately there were desyncs by the minute.

desync report: 
https://drive.google.com/file/d/1xOAQjKkKed_66GFm35dgGlQhh5dzlyJ6/view?usp=sharing

savegame:
https://drive.google.com/file/d/1ve3Z4V8JBPdiar4be7QP1yYI3vC4deF9/view?usp=sharing

modsettings
https://drive.google.com/file/d/1GVX_UHNRWK2Qy_2_VObKQHLqEmPocSTo/view?usp=sharing

modlist: 

 alien-biomes_0.5.8.zip
 Squeak Through_1.8.0.zip
 AutoDeconstruct_0.1.20.zip
 Bottleneck_0.11.4.zip
 even-distribution_0.3.18.zip
 far-reach_1.0.1.zip
 bullet-trails_0.5.1.zip
 Todo-List_18.0.1.zip
 AfraidOfTheDark_1.0.25.zip
 Flow Control_3.0.6.zip
 WaterWell_1.0.21.zip
 Rampant_0.18.17.zip
 RampantResources_0.18.1.zip
 Honk_4.1.0.zip
 Teleporters_0.2.3.zip
 RampantArsenal_1.0.0.zip
 flib_0.4.1.zip
 Flare Stack_2.2.7.zip
 stdlib_1.4.5.zip
 LoaderRedux_1.5.3.zip
 LogisticTrainNetwork_1.14.5.zip
 Nanobots_3.2.10.zip
 qol_research_3.2.0.zip
 spidertron-extended_0.3.3.zip

{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "AfraidOfTheDark",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "AutoDeconstruct",
      "enabled": true
    },
    
    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "bullet-trails",
      "enabled": true
    },
    
    {
      "name": "even-distribution",
      "enabled": true
    },
    
    {
      "name": "far-reach",
      "enabled": true
    },
    
    {
      "name": "Flare Stack",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "Flow Control",
      "enabled": true
    },
    
    {
      "name": "Honk",
      "enabled": true
    },
    
    {
      "name": "LoaderRedux",
      "enabled": true
    },
    
    {
      "name": "LogisticTrainNetwork",
      "enabled": true
    },
    
    {
      "name": "Nanobots",
      "enabled": true
    },
    
    {
      "name": "qol_research",
      "enabled": true
    },
    
    {
      "name": "Rampant",
      "enabled": true
    },
    
    {
      "name": "RampantArsenal",
      "enabled": true
    },
    
    {
      "name": "RampantResources",
      "enabled": true
    },
    
    {
      "name": "spidertron-extended",
      "enabled": true
    },
    
    {
      "name": "Squeak Through",
      "enabled": false
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "Teleporters",
      "enabled": true
    },
    
    {
      "name": "Todo-List",
      "enabled": true
    },
    
    {
      "name": "WaterWell",
      "enabled": true
    }
  ]
}

**Comment by wanderlustzoe** [comment]
ZOMG!!! IM having the same issue! please fix!!!

**Comment by veden** [comment]
how did you determine that Rampant is at fault?

**Comment by veden** [comment]
It looks the random seed for the map is out of sync + alot of other stuff that I have no idea about.
I have no clue as to how to fix this.

**Comment by Phozoh** [comment]
I'm getting desync on headless multiplayer, random frequency (usually within 0-15 minutes), sometimes in the middle of initial "catching up" joining phase.

No issues when locally hosting same multiplayer, didnt desync for 2 hours.

Had a particularly easy start to the game, little pollution, infrequent desync for the start of the game, desyncs seems to happen much more frequently when pollution is touching biter bases or while we attack them with no pollution touching.

Removing Rampant, left an empty map, was able to find enemy by generating new chunks but since pollution wasn't touching anything anymore, no desync for 1 hour.

Setting difficulty scaling to 100 and attack groups size to 600 did not noticeably change frequency of desync, did severely affect UPS when testing on local multiplayer with no desyncs for over 1 hour, base under constant assault. 

Disabling all mods except rampant, and rampant arsenal, still get desync.

Map, Modlist, before and after desync reports in drive link below.
https://drive.google.com/drive/folders/1hJKffY5jLwGL9LXvmeDFxdwqy3pykYHk?usp=sharing

Anything that can be done is humbly appreciated.

**Comment by veden** [comment]
#37 continuing conversation there
