### ISSUE TITLE
Poison biter explosion deals damage to walls

### ISSUE THREAD

**Issue by JohannesGaessler** [veden/Rampant#80]
The poison explosion caused by poison biters upon death deals damage to walls (and presumably other structures too).
This does not seem intended.
In terms of gameplay it's also extremely annoying because walls have no poison resistance and are quickly destroyed if a few biters manage to get in melee range.

**Comment by garrotte13** [comment]
This is an intended behavior. Kill them before they come up. As I remember they are sensible to laser damage.

If all special features of all factions is to be turned off, because it leads to no-go with standard vanilla gameplay, then Rampant New Enemies will be no a mod and mode to play with. Players run New Enemies, because are tired of stupid vanilla Factorio fauna.

**Comment by garrotte13** [comment]
probably you didn't face Nuclear faction yet... a surprise awaits you... :-)

**Comment by JohannesGaessler** [comment]
I was assuming it's a bug because it makes no sense thematically: normally poison damage can only affect breathing entities so I planned out my mining outpost based on wrong assumptions.
(The in-game option actually does mention that the explosion damages structures but I had already forgotten about it a few hours into the game.)

>Kill them before they come up.

Honestly if you have enough resources to do that I think the game is still too easy.

>probably you didn't face Nuclear faction yet... a surprise awaits you... :-)

Already disabled that faction because it seems very gimmicky.

**Comment by garrotte13** [comment]
Yes, you're right. It's a mix of two independent concepts here - type of damage/resistance and idea of cloud gas inhaled.
As I remember in vanilla game only poison capsules produce cloud. In Rampant and Rampant Arsenal there are many damage sources with a cloud produced as a type of damage delivery over time, while delivering different types of damage. Probably it was convient for Veden to select poison type of damage when implementing such enemies that leave DoT effect on the place of their death (which also heals other enemies while damaging player's structures). Therefore it may confuse at first.

>Honestly if you have enough resources to do that I think the game is still too easy.

For me it's not always happening even with enough resources when I set appropriate map difficulty and 10 max enemy tier.

>Already disabled that faction because it seems very gimmicky.

Explosion damage type is the easiest to scale up and second easiest to apply to big areas (at least in Rampant Arsenal), so proper combination of turrets should make it safe. Anyway as they only appear somewhere around 90% evolution player has plenty of time to prepare correct defenses.

**Comment by veden** [comment]
@JohannesGaessler 
Yes, the cloud should damage structures. Are you playing with any weapon mods? Thematically think of it as an acid cloud. Do you have a recommendation for alternative behavior?
I'm open to suggestions to make things less gimmicky for the different types of enemies, do you have any suggestions?

**Comment by JohannesGaessler** [comment]
>Are you playing with any weapon mods?

Bob's Arsenal but I'm only using things that aren't blatantly overpowered like sniper turrets and plasma turrets.

>Thematically think of it as an acid cloud.

The thing is that there already is acid as a damage type which behaves very differently.
Poison as a damage type does normally only affect biological units and even then not biological structures (in vanilla).
My point is that the effects of the poison cloud are simply unintuitive which is undesirable in terms of game design.

>Do you have a recommendation for alternative behavior?

I don't have a concrete proposal for a different behavior regarding the poison cloud short of a complete removal or overhaul.
I personally think the concept is fundamentally flawed because in practice the poison biters play out the same as the exploding biters except they still have their attack and a damage type which walls and other structures have no resistance to.

>I'm open to suggestions to make things less gimmicky for the different types of enemies, do you have any suggestions?

Perhaps gimmicky was the wrong word.
What I don't like about the nuclear biters is that they impose very harsh punishments on you if even one of them gets in range.
I found this frustrating because clearing biter nests results in additional attack waves so this heavily incentivizes you to artificially slow down.
(I personally dislike game mechanics that punish players for being proactive. Also with Rampant Arsenal they are supposedly less of a problem but I can't say anything about that.)

**Comment by veden** [comment]
It sounds like you should toggle those two factions off then.

If you have ideas on how to remove a fundamental flaw in the poison or nuclear factions, let me know. I'm open to suggestions.

**Comment by garrotte13** [comment]
@JohannesGaessler 
Concerning Nuclear:
Factorio already has "forgiveness" mechanisms for players in virtually endless resources (go and take them), and player re-spawning. Why shouldn't some factions do lethal one-time damage if it is their only feature? You can always turn them off.
Unfortunately Factorio modding API and general game logics have some limitations, therefore there always will be some compromise when modders add something to the game. For example Factorio doesn't allow turrets to be smarter to select appropriate targets with higher priority. And there are flaws in biters pathfinding logics on the other side - Veden solved them by biters attacking destroyable path obstructing objects (rocks, trees, cliffs).

Concerning Poison faction... Factorio is about automation and some mechanical structures are expected to defend against attacking biters, not players' chars or other biters - the idea of gas to be inhaled by some living creature is not the feature that will allow biters to prevail in such battle. Probably poison biters in Rampant could apply some corrosion agent fluid on buildings in area around their dead bodies. E.g. in my mod I use creep corrosion as DoT instead of gas cloud :-)
