### ISSUE TITLE
Inferno spitters one-shot turrets

### ISSUE THREAD

**Issue by JohannesGaessler** [veden/Rampant#81]
One attack from an inferno spitter is enough to completely kill a turret (gun turret MK2 from Bob's Warfare) by setting it on fire.
This does not seem intended.

**Comment by garrotte13** [comment]
This is an old well-known behavior (can be found in several mod portal threads). When playing with New Enemies it is highly recommended to play with Rampant Arsenal (it means no Bob's or similar conflicting mods - you'll die with Bobs anyway unless you start cheating with plasma weapons... boring) and use poison bullets/rockets - inferno spitters die very fast from poison damage and as Veden added a special time pause before spitters fire, it became a no problem.
Another solution is to turn off Inferno faction if one can't use poison ammo due to his/her mods setup.

**Comment by JohannesGaessler** [comment]
I think changing the description of the inferno faction might be a good idea.
I interpreted "flaming acid that burns everything" to mean that they ignore resistances, not that their dot deals large amount of damage.

Also if another mod is recommended when enabling new enemies the I think the mod page should mention this.

**Comment by garrotte13** [comment]
Inferno faction has two more uncertainities besides this small one-time, but very heavy damage-over-time attack:
- applying acid damage while being red-colored and having red flames animation for damage. Player can think, that it is fire damage for which player's structure have big resistance, especially 100% for walls. But that's easy to get used to after some playing;
- this acid DoT produces pollution. Especially when inferno spitter is attacking trees to remove obstacles and starts forest fires. That's a thing I can't get used to - acid, native-friendly damage creates bad pollution like human-intruder does.

**Comment by veden** [comment]
@JohannesGaessler 
> I think changing the description of the inferno faction might be a good idea.
> Also if another mod is recommended when enabling new enemies the I think the mod page should mention this.

I'm open to merge requests for the change

How is ignore resistances different than large amounts of damage?
Happy to hear recommendations on fixing the issues.

**Comment by veden** [comment]
Inferno faction should have a significantly reduced DPS in the version on the master branch

**Comment by JohannesGaessler** [comment]
>How is ignore resistances different than large amounts of damage?

The difference is important when considering the effective HP of different entities.
As an example, walls have 350 HP, 80% acid resistance, and 100% fire resistance.
Laser turrets have 1000 HP and no resistances.
So against an attack that is equal parts fire and acid damage walls effectively have 3500 HP while laser turrets effectively have 1000 HP.
Conversely, against an attack that completely ignores resistances walls effectively have 350 HP while laser turrets effectively have 1000 HP.
At least for me this influences the proportion of walls to turrets that I put down and, much space I put between walls and turrets, and how valuable I find cliffs to be because attacks against walls vs. turrets are very different in terms of how dangerous they are.

**Comment by garrotte13** [comment]
@JohannesGaessler 
Walls have 30%-70% fire resistance (unless one plays in cheat mode)
Of course one must never ever put walls adjacent to turrets - there must be one or two free tiles between them (depending on playthrough progress and inferno faction appearance is not game beginning).
Probably the only good solution here is to add some basic % acid resistance for all vanilla turrets (some 20..30%), but definitely not 60% :-) .

Also I do recommend to play with Rampant Arsenal or turn off half of new enemies factions: Inferno, Poison, Laser, Nuclear, ... That's absolutely logical. When I played Rampant and Krastorio I turned off Poison and Inferno, because K2 fails against them in everything (no damage protection in end game armors, no correct damage type to counter-attack and so on). And of course I didn't set max tier more than 6 for such playthrough. Max biter tier 7+ are only for Rampant Arsenal games.

@veden
IMHO reducing damage of inferno spitters was a bad idea, because this is the key feature of this faction. Those spitters are absolutely harmless against moving vehicles/chars. Also they are not well defended, so their only chance to harm player is to make a one lucky strike at player's turrets.
Now Rampant new enemies can get another dead faction like it already happened to suicide biters.

**Comment by veden** [comment]
To be clear I appreciate both of you providing input into this discussion.

@JohannesGaessler 
Understood about updating the faction description.

I'm trying to understand how to improve the game design, the reason I ask is because you have identified something as having a bad design which means that you should have an opinion on how to fix it or are you just telling me you don't like something and you don't know how you would fix it?

@garrotte13 
After someplay testing with the inferno faction yesterday, the inferno faction will probably undergo some additional changes still.
